site_name: GyrSec
site_url: https://gyrsec.github.io/gyrsec
repo_url: https://github.com/gyrsec/gyrsec.github.io
repo_name: gyrsec/gyrsec.github.io
theme:
  name: material
  palette: 
    scheme: slate
    primary: black
    icon: material/brightness-4
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gyrsec
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/gyrsec
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jacob-roberts-478a25138
    - icon: fontawesome/solid/paper-plane
      link: mailto:gyrsec@proton.me
copyright: Copyright &copy; 2024 Jacob Roberts